name: Build Go Hass Cards

on:
  workflow_call:

jobs:
  build:
    name: Build Go Hass Cards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install node modules
        run: bun install

      - name: Build the project
        run: bun run build

      - name: Upload Go Hass Cards as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Go Hass Cards
          path: dist
