name: Lint Project

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install node modules
        run: bun install

      - name: Lint the project
        run: bun run lint
